apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: detection-app
  namespace: ezdehar-argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Ezdehar-Jayosi/Object-Detection-Service-bot
    targetValue: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: ezdeharj


syncPolicy:
  automated:
    selfHeal: true
    prune: true