apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: detection-app
  namespace: ezdehar-argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Ezdehar-Jayosi/Object-Detection-Service-bot
    targetRevision: HEAD  # Corrected field name
    path: k8s  # Specify the path to your Kubernetes manifests within the repository

  destination:
    server: https://kubernetes.default.svc
    namespace: ezdeharj

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
